[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.6.11"
regex = "1"
log = "0.4"
env_logger = "0.8"
structopt = "0.3"
anyhow = "1.0"
